[package]
name = "canister_factory"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]
path = "lib.rs"

[dependencies]
candid = "0.10.10"
ic-cdk = "0.18.3"
serde = { version = "1", features = ["derive"] }
